### ISSUE TITLE
Localized error message

### ISSUE THREAD

**Issue by rswhite7** [alecritson/Craft-Password-Confirm#1]
Hi, I'm not a php expert, so how could I add a line to the plugin's code to accommodate for a second locale other than just English?

**Comment by alecritson** [comment]
Hey @rswhite7 

You don't need to know php or edit the plugins code, the error message using [static translations](https://craftcms.com/support/static-translations) so all you need to do is:

Create a php file in `craft/translations` with the file name of the locale you wish to use i.e `fr.php` then in this file you would just do a one for one translation like:

```
<?php
return array(
  'Passwords do not match` => 'Les mots de passe ne correspondent pas`
);
?>
```

Hope that helps!

**Comment by rswhite7** [comment]
Thanks so much!
