### ISSUE TITLE
Using plugin with user update profile form

### ISSUE THREAD

**Issue by rswhite7** [alecritson/Craft-Password-Confirm#2]
Is it possible to use this plugin for the user update profile form as demonstrated here:
https://craftcms.com/docs/templating/user-profile-form

I noticed that your plugin checks the value of `passwordConfirm` against an input called `password`, but if you have a form that allows a logged in user to update their password, it would need to check it against `newPassword`. Is it possible to do this currently with your plugin?

This is an issue I think is necessary for the plugin, since if you have a front-end registration form to sign users up, there most likely will be an area in most people's sites where the user can change their information and authentication credentials, and it took me awhile to realize the plugin was causing validation errors despite having removed it from my update user profile form :/

**Comment by alecritson** [comment]
Hey @rswhite7 

Sorry it took a while to get back to this, I have just pushed an update which now means the plugin will only check for matching passwords if the `passwordConfirm` field is present.

Hopefully that will solve your issue.

**Comment by rswhite7** [comment]
No worries, thanks for the update!

**Comment by OliverMaerz** [comment]
This seems to cause an issue when the passwordConfirm field is left empty by the user. So registration form has both the password and passwordConfirm field. If user only fills out password field (and leaves passwordConfirm empty) then no error is displayed and user is registered.
